CREATE TABLE hlv (
  id INT AUTO_INCREMENT PRIMARY KEY,
  SupplierName VARCHAR(50) NOT NULL,
  Address VARCHAR(50) NOT NULL,
  ContactInformation VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  ProductName VARCHAR(50) NOT NULL,
  Description VARCHAR(50) NOT NULL,
  Units VARCHAR(50) NOT NULL,
  Quantity VARCHAR(50) NOT NULL,
  Amount VARCHAR(50) NOT NULL,
  ModeOfPayment VARCHAR(50) NOT NULL,
  TermsOfPayment VARCHAR(50) NOT NULL,
  OrderedBy VARCHAR(50) NOT NULL,
  OrderDate VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;
